package ctrlfit.telas;

import ctrlfit.conexao.PlanoDAO;
import ctrlfit.entity.Plano;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class CadastroPlano extends javax.swing.JFrame {

    private int codigoAtual;
    private boolean modoAlterar = false;//variavel do tipo boolean, se o usuario clicar em exibir ela é alterar para verdadeiro
    GerenciamentoPlanos gerenciamentoPlanos;

    public CadastroPlano(GerenciamentoPlanos gerenciamentoPlanos) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ctrlfit/icons/logo_haltere2.png")));
        this.gerenciamentoPlanos = gerenciamentoPlanos;
    }

    //construtor para exibir plano
    public CadastroPlano(GerenciamentoPlanos gerenciamentoPlanos, Plano objPlano) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ctrlfit/icons/logo_haltere2.png")));
        this.gerenciamentoPlanos = gerenciamentoPlanos;

        modoAlterar = true;
        this.codigoAtual = objPlano.getCodigo();

        txtNomePlano.setText(objPlano.getNome());
        txtPrecoPlano.setText(String.valueOf(objPlano.getPreco()));
        jComboBoxDuracao.setSelectedIndex(objPlano.getDuracao() - 1);
        txtDescricao.setText(objPlano.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnConfirmarPlano = new javax.swing.JButton();
        btnCancelarPlano = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNomePlano = new javax.swing.JTextField();
        jComboBoxDuracao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrecoPlano = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Plano");
        setResizable(false);

        jLabel6.setText("Descrição:");

        btnConfirmarPlano.setText("Confirmar");
        btnConfirmarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPlanoActionPerformed(evt);
            }
        });

        btnCancelarPlano.setText("Cancelar");
        btnCancelarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPlanoActionPerformed(evt);
            }
        });

        jLabel3.setText("* Preço do plano:");

        jComboBoxDuracao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel1.setText("* Duração (em meses):");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Campos com asterisco (*) são de preenchimento");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("obrigatório");

        jLabel7.setText("* Nome do plano:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnConfirmarPlano)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelarPlano))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomePlano))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecoPlano))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecoPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPlano)
                    .addComponent(btnConfirmarPlano))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPlanoActionPerformed
        if (txtNomePlano.getText().isEmpty() || txtPrecoPlano.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                //obter os valores digitados dos campos
                String nomePlano = txtNomePlano.getText();
                double precoPlano = Double.parseDouble(txtPrecoPlano.getText());

                int opcao = jComboBoxDuracao.getSelectedIndex();
                int duracaoPlano = opcao + 1;

                String descricaoPlano = txtDescricao.getText();

                Plano objPlano = new Plano(codigoAtual, nomePlano, precoPlano, duracaoPlano, descricaoPlano);

                PlanoDAO objPlanoDao = new PlanoDAO();
                if (modoAlterar) {
                    objPlano.setCodigo(codigoAtual);
                    objPlanoDao.alterarPlano(objPlano);
                } else {
                    objPlanoDao.cadastrarPlano(objPlano);
                }

                dispose();
                gerenciamentoPlanos.carregarDadosPlanos();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Digite um preço válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                txtPrecoPlano.setText("");
            }
        }
    }//GEN-LAST:event_btnConfirmarPlanoActionPerformed

    private void btnCancelarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPlanoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarPlanoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPlano;
    private javax.swing.JButton btnConfirmarPlano;
    private javax.swing.JComboBox<String> jComboBoxDuracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNomePlano;
    private javax.swing.JTextField txtPrecoPlano;
    // End of variables declaration//GEN-END:variables

}
