package ctrlfit.telas;

import ctrlfit.conexao.ExercicioDAO;
import ctrlfit.entity.Exercicio;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class CadastroExercicio extends javax.swing.JFrame {

    private GerenciamentoTreinos gerenciamentoTreinos;
    private boolean modoAlterar = false;//variavel do tipo boolean, se o usuario clicar em exibir ela é alterar para verdadeiro
    private int codigoAtual;

    public CadastroExercicio(GerenciamentoTreinos teste) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ctrlfit/icons/logo_haltere2.png")));
        this.gerenciamentoTreinos = teste;
    }

    //construtor para exibir exercicio
    public CadastroExercicio(GerenciamentoTreinos teste, Exercicio objExercicio) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ctrlfit/icons/logo_haltere2.png")));
        this.gerenciamentoTreinos = teste;

        modoAlterar = true;
        this.codigoAtual = objExercicio.getCodigo();

        txtMatriculaAluno.setText(String.valueOf(objExercicio.getMatricula()));

        int aux;
        if (objExercicio.getDivisaoTreino() == 'A') {
            aux = 0;
        } else if (objExercicio.getDivisaoTreino() == 'B') {
            aux = 1;
        } else if (objExercicio.getDivisaoTreino() == 'C') {
            aux = 2;
        } else if (objExercicio.getDivisaoTreino() == 'D') {
            aux = 3;
        } else {
            aux = 4;
        }
        jComboBoxDivisaoTreino.setSelectedIndex(aux);

        txtNomeExercicio.setText(objExercicio.getNome());
        txtNumSeries.setText(String.valueOf(objExercicio.getQuantSeries()));
        txtNumRepeticoes.setText(String.valueOf(objExercicio.getQuantRepeticoes()));
        txtObservacoes.setText(objExercicio.getObservacoes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumRepeticoes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnConfirmarTreino = new javax.swing.JButton();
        btnCancelarTreino = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNumSeries = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMatriculaAluno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDivisaoTreino = new javax.swing.JComboBox<>();
        txtNomeExercicio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Exercício");
        setResizable(false);

        jLabel6.setText("Observações:");

        btnConfirmarTreino.setText("Confirmar");
        btnConfirmarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarTreinoActionPerformed(evt);
            }
        });

        btnCancelarTreino.setText("Cancelar");
        btnCancelarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTreinoActionPerformed(evt);
            }
        });

        jLabel3.setText("* Nº de Séries:");

        jLabel4.setText("* Matrícula do aluno:");

        jLabel5.setText("* Nº de repetições:");

        jLabel2.setText("* Divisão do treino:");

        jComboBoxDivisaoTreino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));

        jLabel7.setText("* Nome do exercício:");

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane1.setViewportView(txtObservacoes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Campos com asterisco (*) são de preenchimento obrigatório");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxDivisaoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNomeExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(txtNumSeries)
                                        .addComponent(txtNumRepeticoes))
                                    .addComponent(txtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarTreino)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarTreino)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDivisaoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomeExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNumRepeticoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarTreino)
                    .addComponent(btnConfirmarTreino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTreinoActionPerformed
        if (txtMatriculaAluno.getText().isEmpty() || txtNomeExercicio.getText().isEmpty()
                || txtNumSeries.getText().isEmpty() || txtNumRepeticoes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                //obter os valores digitados dos campos
                int matricula = Integer.parseInt(txtMatriculaAluno.getText());

                ExercicioDAO objExercicioDao = new ExercicioDAO();

                // Verificar se a matrícula existe
                if (!objExercicioDao.verificarMatriculaExistente(matricula)) {
                    JOptionPane.showMessageDialog(null, "A matrícula do aluno não existe. Verifique e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                char divisaoTreino = 'A';
                if (jComboBoxDivisaoTreino.getSelectedIndex() == 0) {
                    divisaoTreino = 'A';
                } else if (jComboBoxDivisaoTreino.getSelectedIndex() == 1) {
                    divisaoTreino = 'B';
                } else if (jComboBoxDivisaoTreino.getSelectedIndex() == 2) {
                    divisaoTreino = 'C';
                } else if (jComboBoxDivisaoTreino.getSelectedIndex() == 3) {
                    divisaoTreino = 'D';
                } else {
                    divisaoTreino = 'E';
                }

                String nomeExercicio = txtNomeExercicio.getText();
                int numSeries = Integer.parseInt(txtNumSeries.getText());
                int numRepeticoes = Integer.parseInt(txtNumRepeticoes.getText());
                String observacoes = txtObservacoes.getText();

                Exercicio objExercicio = new Exercicio(codigoAtual, matricula, divisaoTreino, nomeExercicio, numSeries, numRepeticoes, observacoes);

                if (modoAlterar) {
                    //alterar();
                    objExercicio.setCodigo(codigoAtual);

                    objExercicioDao.alterarExercicio(objExercicio);
                } else {
                    //cadastrar();
                    objExercicioDao.cadastrarExercicio(objExercicio);
                }

                dispose();
                gerenciamentoTreinos.carregarDadosTreinos();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Digite um número válido para matrícula, séries e repetições.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnConfirmarTreinoActionPerformed

    private void btnCancelarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTreinoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarTreinoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTreino;
    private javax.swing.JButton btnConfirmarTreino;
    private javax.swing.JComboBox<String> jComboBoxDivisaoTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtMatriculaAluno;
    private javax.swing.JTextField txtNomeExercicio;
    private javax.swing.JTextField txtNumRepeticoes;
    private javax.swing.JTextField txtNumSeries;
    private javax.swing.JTextArea txtObservacoes;
    // End of variables declaration//GEN-END:variables

}
