package ctrlfit.telas;

import ctrlfit.conexao.FuncionarioDAO;
import ctrlfit.entity.Funcionario;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class CadastroFuncionario extends javax.swing.JFrame {

    private GerenciamentoFuncionarios gerenciamentoFuncionarios;
    private boolean modoAlterar = false;//variavel do tipo boolean, se o usuario clicar em exibir ela é alterar para verdadeiro
    private int codigoAtual;

    public CadastroFuncionario(GerenciamentoFuncionarios teste) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ctrlfit/icons/logo_haltere2.png")));
        this.gerenciamentoFuncionarios = teste;
    }

    //construtor para exibir funcionario
    public CadastroFuncionario(GerenciamentoFuncionarios teste, Funcionario objFuncionario) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ctrlfit/icons/logo_haltere2.png")));
        this.gerenciamentoFuncionarios = teste;

        modoAlterar = true;
        this.codigoAtual = objFuncionario.getCodigo();
        txtNomeFunc.setText(objFuncionario.getNome());
        jComboBoxCargoFunc.setSelectedItem(objFuncionario.getCargo());
        txtCpfFunc.setText(objFuncionario.getCpf());
        txtTelefoneFunc.setText(objFuncionario.getTelefone());
        txtCelularFunc.setText(objFuncionario.getCelular());
        txtEnderecoFunc.setText(objFuncionario.getEndereco());
        txtBairroFunc.setText(objFuncionario.getBairro());
        txtCepFunc.setText(objFuncionario.getCep());
        txtEmailFunc.setText(objFuncionario.getEmail());
        txtUsuarioFunc.setText(objFuncionario.getUsuario());
        txtSenhaFunc.setText(objFuncionario.getSenha());
        txtSalarioFunc.setText(String.valueOf(objFuncionario.getSalario()));
        jComboBoxSexoFunc.setSelectedItem(String.valueOf(objFuncionario.getSexo()));

        //datas
        // Definindo o formato desejado
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        // Formatando a data e definindo o texto no JTextField
        txtDtNascimentoFunc.setText(formato.format(objFuncionario.getDtNascimento()));
        txtDtAdmissaoFunc.setText(formato.format(objFuncionario.getDtAdmissao()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtEnderecoFunc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmailFunc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtSenhaFunc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuarioFunc = new javax.swing.JTextField();
        jComboBoxSexoFunc = new javax.swing.JComboBox<>();
        txtCpfFunc = new javax.swing.JFormattedTextField();
        txtCepFunc = new javax.swing.JFormattedTextField();
        txtTelefoneFunc = new javax.swing.JFormattedTextField();
        txtCelularFunc = new javax.swing.JFormattedTextField();
        txtDtNascimentoFunc = new javax.swing.JFormattedTextField();
        txtDtAdmissaoFunc = new javax.swing.JFormattedTextField();
        txtSalarioFunc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNomeFunc = new javax.swing.JTextField();
        txtBairroFunc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCargoFunc = new javax.swing.JComboBox<>();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setResizable(false);

        jLabel2.setText("* Endereço:");

        jLabel4.setText("* Data de Nascimento: ");

        jLabel5.setText("* Bairro:");

        jLabel6.setText("* Sexo: ");

        jLabel7.setText("Telefone:");

        jLabel8.setText("* Celular:");

        jLabel9.setText("Email:");

        jLabel10.setText("* CEP:");

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel13.setText("Senha:");

        jLabel14.setText("* Salário:");

        jLabel15.setText("* Data de admissão:");

        jLabel17.setText("* Cargo:");

        jLabel3.setText("Usuário:");

        jComboBoxSexoFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "O" }));

        try {
            txtCpfFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCepFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtTelefoneFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCelularFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDtNascimentoFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDtAdmissaoFunc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("* Nome:");

        jLabel12.setText("* CPF:");

        jLabel1.setText("Campos com asterisco (*) são de preenchimento obrigatório");

        jComboBoxCargoFunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepcionista", "Instrutor", "Gerente", "Outro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtAdmissaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDtNascimentoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBoxSexoFunc, 0, 1, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel17)
                                            .addGap(18, 18, 18)
                                            .addComponent(jComboBoxCargoFunc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtBairroFunc))
                                        .addComponent(txtEnderecoFunc)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtTelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCelularFunc))
                                        .addComponent(txtEmailFunc)
                                        .addComponent(txtUsuarioFunc)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSalarioFunc))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnConfirmar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCancelar)))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBoxCargoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDtNascimentoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSexoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEnderecoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtBairroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefoneFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCelularFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDtAdmissaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        String nome, cpf, cargo, endereco, cep, bairro, telefone, celular, email, usuario, senha;
        Date dtNascimento = null, dtAdmissao = null;
        double salario;
        char sexo = ' ';

        nome = txtNomeFunc.getText();
        cpf = txtCpfFunc.getText();
        cargo = (String) jComboBoxCargoFunc.getSelectedItem();
        endereco = txtEnderecoFunc.getText();
        cep = txtCepFunc.getText();
        bairro = txtBairroFunc.getText();
        telefone = txtTelefoneFunc.getText();
        celular = txtCelularFunc.getText();
        email = txtEmailFunc.getText();
        usuario = txtUsuarioFunc.getText();
        senha = txtSenhaFunc.getText();

        String sexoString = (String) jComboBoxSexoFunc.getSelectedItem();
        sexo = sexoString.charAt(0);

        String cpfVazio = "   .   .   -  ";
        String cepVazio = "     -   ";
        String celularVazio = "(  )     -    ";

        // Verificar se os campos estão vazios
        if (nome.isEmpty() || cpf.equals(cpfVazio)
                || endereco.isEmpty()
                || cep.equals(cepVazio) || bairro.isEmpty()
                || celular.equals(celularVazio) || txtSalarioFunc.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios.", "Aviso", JOptionPane.WARNING_MESSAGE);

        } else {
            try {

                salario = Double.valueOf(txtSalarioFunc.getText());

                //pegando as datas digitadas
                try {
                    // Defina o formato da data que você deseja receber
                    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

                    // Defina que o formato não deve permitir datas inválidas (como 32/13/2023)
                    formato.setLenient(false);

                    // Converta o texto para o objeto Date
                    dtNascimento = formato.parse(txtDtNascimentoFunc.getText());
                    dtAdmissao = formato.parse(txtDtAdmissaoFunc.getText());
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(null, "Formato de data inválido.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;

                }

                //funcionario = new Funcionario(codigoAtual, nome, cargo, cpf, dtNascimento, telefone, celular, endereco, bairro, cep, sexo, salario, dtAdmissao, email, usuario, senha);
                Funcionario objFuncionario = new Funcionario(codigoAtual, nome, cargo, cpf, dtNascimento, telefone, celular, endereco, bairro, cep, sexo, salario, dtAdmissao, email, usuario, senha);

                FuncionarioDAO objFuncionarioDao = new FuncionarioDAO();

                if (modoAlterar) {
                    objFuncionario.setCodigo(codigoAtual);

                    if (objFuncionarioDao.verificarCpf(objFuncionario, modoAlterar)) {
                        JOptionPane.showMessageDialog(null, "O CPF " + objFuncionario.getCpf() + " já está cadastrado no sistema.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    } else {
                        objFuncionarioDao.alterarFuncionario(objFuncionario);
                        dispose();
                        gerenciamentoFuncionarios.carregarDadosFuncionarios();
                    }
                } else {
                    if (objFuncionarioDao.verificarCpf(objFuncionario, modoAlterar)) {
                        JOptionPane.showMessageDialog(null, "O CPF " + objFuncionario.getCpf() + " já está cadastrado no sistema.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    } else {
                        objFuncionarioDao.cadastrarFuncionario(objFuncionario);
                        dispose();
                        gerenciamentoFuncionarios.carregarDadosFuncionarios();
                    }
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Digite um salário válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                txtSalarioFunc.setText("");
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JComboBox<String> jComboBoxCargoFunc;
    private javax.swing.JComboBox<String> jComboBoxSexoFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txtBairroFunc;
    private javax.swing.JFormattedTextField txtCelularFunc;
    private javax.swing.JFormattedTextField txtCepFunc;
    private javax.swing.JFormattedTextField txtCpfFunc;
    private javax.swing.JFormattedTextField txtDtAdmissaoFunc;
    private javax.swing.JFormattedTextField txtDtNascimentoFunc;
    private javax.swing.JTextField txtEmailFunc;
    private javax.swing.JTextField txtEnderecoFunc;
    private javax.swing.JTextField txtNomeFunc;
    private javax.swing.JTextField txtSalarioFunc;
    private javax.swing.JTextField txtSenhaFunc;
    private javax.swing.JFormattedTextField txtTelefoneFunc;
    private javax.swing.JTextField txtUsuarioFunc;
    // End of variables declaration//GEN-END:variables

}
