package ctrlfit.telas;

import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class TelaInicial extends javax.swing.JFrame {

    private GerenciamentoAlunos gerenciamentoAlunos;
    private GerenciamentoPagamentos gerenciamentoPagamentos;
    private GerenciamentoTreinos gerenciamentoTreinos;
    private GerenciamentoPlanos gerenciamentoPlanos;
    private GerenciamentoFuncionarios gerenciamentoFuncionarios;

    //construtor que recebe como parametro o cargo para verificar usuario
    public TelaInicial(String cargo) {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);//maximizar tela
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/ctrlfit/icons/logo_haltere2.png")));//icone da janela

        //JOptionPane.showMessageDialog(null, cargo); //cargo recebido
        if (cargo.equalsIgnoreCase("Recepcionista")) {
            btnTreinos.setEnabled(false);
            btnPlanos.setEnabled(false);
            btnFuncionarios.setEnabled(false);

            jMenuItemTreinos.setEnabled(false);
            jMenuItemPlanos.setEnabled(false);
            jMenuItemFuncionarios.setEnabled(false);
        }
        if (cargo.equalsIgnoreCase("Instrutor")) {
            btnPagamentos.setEnabled(false);
            btnPlanos.setEnabled(false);
            btnFuncionarios.setEnabled(false);

            jMenuItemPagamentos.setEnabled(false);
            jMenuItemPlanos.setEnabled(false);
            jMenuItemFuncionarios.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAlunos = new javax.swing.JButton();
        btnPagamentos = new javax.swing.JButton();
        btnTreinos = new javax.swing.JButton();
        btnPlanos = new javax.swing.JButton();
        btnFuncionarios = new javax.swing.JButton();
        btnLogoff = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemAlunos = new javax.swing.JMenuItem();
        jMenuItemPagamentos = new javax.swing.JMenuItem();
        jMenuItemTreinos = new javax.swing.JMenuItem();
        jMenuItemPlanos = new javax.swing.JMenuItem();
        jMenuItemFuncionarios = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jMenuFechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial - Ctrl Fit");

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        btnAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrlfit/icons/alunos_resized.png"))); // NOI18N
        btnAlunos.setText("Alunos");
        btnAlunos.setFocusable(false);
        btnAlunos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlunos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlunos);

        btnPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrlfit/icons/pagamentos_resized.png"))); // NOI18N
        btnPagamentos.setText("Pagamentos");
        btnPagamentos.setFocusable(false);
        btnPagamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPagamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagamentosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPagamentos);

        btnTreinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrlfit/icons/treinos_resized.png"))); // NOI18N
        btnTreinos.setText("Treinos");
        btnTreinos.setFocusable(false);
        btnTreinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTreinos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTreinos);

        btnPlanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrlfit/icons/mensalidades_resized.png"))); // NOI18N
        btnPlanos.setText("Planos");
        btnPlanos.setFocusable(false);
        btnPlanos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlanos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlanos);

        btnFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrlfit/icons/funcionarios_resized.png"))); // NOI18N
        btnFuncionarios.setText("Funcionários");
        btnFuncionarios.setFocusable(false);
        btnFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFuncionarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFuncionarios);

        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrlfit/icons/logoff.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.setFocusable(false);
        btnLogoff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogoff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogoff);

        jPanel1.setBackground(new java.awt.Color(10, 75, 166));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ctrlfit/icons/logo_tela_inicial.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jMenuCadastros.setText("Cadastros");

        jMenuItemAlunos.setText("Alunos");
        jMenuItemAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemAlunos);

        jMenuItemPagamentos.setText("Pagamentos");
        jMenuItemPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagamentosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemPagamentos);

        jMenuItemTreinos.setText("Treinos");
        jMenuItemTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTreinosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemTreinos);

        jMenuItemPlanos.setText("Planos");
        jMenuItemPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPlanosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemPlanos);

        jMenuItemFuncionarios.setText("Funcionários");
        jMenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFuncionarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        jMenuFechar.setText("Fechar");
        jMenuFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFecharMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuFechar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(882, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed
        // Abre a tela especificada, garantindo que apenas uma instância esteja visível
        if (gerenciamentoAlunos == null || !gerenciamentoAlunos.isDisplayable()) {
            gerenciamentoAlunos = new GerenciamentoAlunos();
            gerenciamentoAlunos.setVisible(true);
        } else {
            gerenciamentoAlunos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_btnAlunosActionPerformed

    private void btnPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagamentosActionPerformed
        // Abre a tela especificada, garantindo que apenas uma instância esteja visível
        if (gerenciamentoPagamentos == null || !gerenciamentoPagamentos.isDisplayable()) {
            gerenciamentoPagamentos = new GerenciamentoPagamentos();
            gerenciamentoPagamentos.setVisible(true);
        } else {
            gerenciamentoPagamentos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_btnPagamentosActionPerformed

    private void btnTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinosActionPerformed
        // Abre a tela especificada, garantindo que apenas uma instância esteja visível
        if (gerenciamentoTreinos == null || !gerenciamentoTreinos.isDisplayable()) {
            gerenciamentoTreinos = new GerenciamentoTreinos();
            gerenciamentoTreinos.setVisible(true);
        } else {
            gerenciamentoTreinos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_btnTreinosActionPerformed

    private void btnPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanosActionPerformed
        // Abre a tela especificada, garantindo que apenas uma instância esteja visível
        if (gerenciamentoPlanos == null || !gerenciamentoPlanos.isDisplayable()) {
            gerenciamentoPlanos = new GerenciamentoPlanos();
            gerenciamentoPlanos.setVisible(true);
        } else {
            gerenciamentoPlanos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_btnPlanosActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        // Abre a tela especificada, garantindo que apenas uma instância esteja visível
        if (gerenciamentoFuncionarios == null || !gerenciamentoFuncionarios.isDisplayable()) {
            gerenciamentoFuncionarios = new GerenciamentoFuncionarios();
            gerenciamentoFuncionarios.setVisible(true);
        } else {
            gerenciamentoFuncionarios.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        Object[] opcoes = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(
                this,
                "Você tem certeza que deseja sair da conta atual?",
                "Logoff",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // Ícone padrão
                opcoes, // Opções de botões personalizadas
                opcoes[0] // Opção padrão selecionada
        );

        if (resposta == JOptionPane.YES_OPTION) {
            // Fecha todas as janelas abertas, exceto a tela de login
            for (Window window : Window.getWindows()) {
                if (window instanceof JFrame && window.isShowing()) {
                    window.dispose(); // Fecha a janela
                }
            }

            // Abre a tela de login
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void jMenuItemAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunosActionPerformed
        if (gerenciamentoAlunos == null || !gerenciamentoAlunos.isDisplayable()) {
            gerenciamentoAlunos = new GerenciamentoAlunos();
            gerenciamentoAlunos.setVisible(true);
        } else {
            gerenciamentoAlunos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_jMenuItemAlunosActionPerformed

    private void jMenuItemPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagamentosActionPerformed
        if (gerenciamentoPagamentos == null || !gerenciamentoPagamentos.isDisplayable()) {
            gerenciamentoPagamentos = new GerenciamentoPagamentos();
            gerenciamentoPagamentos.setVisible(true);
        } else {
            gerenciamentoPagamentos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_jMenuItemPagamentosActionPerformed

    private void jMenuItemTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTreinosActionPerformed
        if (gerenciamentoTreinos == null || !gerenciamentoTreinos.isDisplayable()) {
            gerenciamentoTreinos = new GerenciamentoTreinos();
            gerenciamentoTreinos.setVisible(true);
        } else {
            gerenciamentoTreinos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_jMenuItemTreinosActionPerformed

    private void jMenuItemPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPlanosActionPerformed
        if (gerenciamentoPlanos == null || !gerenciamentoPlanos.isDisplayable()) {
            gerenciamentoPlanos = new GerenciamentoPlanos();
            gerenciamentoPlanos.setVisible(true);
        } else {
            gerenciamentoPlanos.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_jMenuItemPlanosActionPerformed

    private void jMenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionariosActionPerformed
        if (gerenciamentoFuncionarios == null || !gerenciamentoFuncionarios.isDisplayable()) {
            gerenciamentoFuncionarios = new GerenciamentoFuncionarios();
            gerenciamentoFuncionarios.setVisible(true);
        } else {
            gerenciamentoFuncionarios.toFront(); // Traz a janela para frente se já estiver aberta
        }
    }//GEN-LAST:event_jMenuItemFuncionariosActionPerformed

    private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
        JOptionPane.showMessageDialog(null,
                "CTRL FIT é um sistema para o gerenciamaneto de academias.\n"
                + "Com foco na simplicidade e objetividade, ele permite controlar\n"
                + "alunos, pagamentos, treinos, planos e funcionários. Ideal para\n"
                + "academias que desejam abandonar o uso de papel ou planilhas,\n"
                + "o CTRL FIT proporciona uma gestão moderna e otimizada,\n"
                + "garantindo mais organização e praticidade no dia a dia.\n"
                + "\nAutores:\n"
                + "Augusto dos Santos Silva - 33090416\n"
                + "João Vittor Fontes - 33625291\n"
                + "Matheus Gonçalves Gomes de Souza - 34740597\n"
                + "Raul Tonti Sorbara - 32764812\n"
                + "Vyctor Santos do Nascimento Bezerra – 3307315", "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuSobreMouseClicked

    private void jMenuFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFecharMouseClicked
        Object[] opcoes = {"Sim", "Não"};
        int resposta = JOptionPane.showOptionDialog(
                this,
                "Você tem certeza que deseja encerrar a aplicação?",
                "Encerrar aplicação",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // Ícone padrão
                opcoes, // Opções de botões personalizadas
                opcoes[0] // Opção padrão selecionada
        );

        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuFecharMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton btnPagamentos;
    private javax.swing.JButton btnPlanos;
    private javax.swing.JButton btnTreinos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFechar;
    private javax.swing.JMenuItem jMenuItemAlunos;
    private javax.swing.JMenuItem jMenuItemFuncionarios;
    private javax.swing.JMenuItem jMenuItemPagamentos;
    private javax.swing.JMenuItem jMenuItemPlanos;
    private javax.swing.JMenuItem jMenuItemTreinos;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
